### ISSUE TITLE
Error when trying to run the baseline mlp model

### ISSUE THREAD

**Issue by correiav** [sominwadhwa/vqamd_floyd#1]
Hi @sominwadhwa !
Thank you for sharing your work!

I was trying to train the baseline MLP model but I got the following error:
`ValueError: Error when checking input: expected dense_1_input to have shape (4396,) but got array with shape (4096,)`. Would you, by any chance, have an idea on why it happens? 
Also, just a fyi, the shape of the `dense_5 (Dense)` and `activation_4 (Activation)` layers look like: `(None, 22706) `, however I'm compiling the model like you. 

I'd appreciate if you have any thoughts to share! 
Thank you =)

**Comment by sominwadhwa** [comment]
Hi @correiav , Could you please check what are the dimensions of your word vectors generated by `SpaCy` language models? They should be `300`. The `expected` shape is by logic derived from `4096` (image features) + `300` wordVec dimensions.

**Comment by correiav** [comment]
Hey @sominwadhwa !
Thank you very much for your quick response! You were right the problem was the dimension of the word vectors generated by `spacy`. For some reason, I couldn't make it work by using `nlp = spacy.load("en")` so after doing a little research, using `nlp = spacy.load('en_vectors_web_lg')` worked for me, now the model is running. Once again, thank you very much!
